language: python

python: 
    - "3.6"

install:
    - pip install -r requirements.txt

script:
#     - pytest -v --cov ireporter --cov-report term-missing 
- pytest
    
after_success:
    - coveralls
